if(len(INN)>10&&len(OUT)>10)
    print("H1- High Risk customer")
if(sum(INN)>1000)
    print("H2- High Risk customer")
if(sum(OUT)>800)
    print("H3- High Risk customer")
if(len(INN)+len(OUT)>20)
    print("H4- High Risk customer")

if(len(INN)>6&&len(OUT)>6)
    print("M1- Medium Risk customer")
if(sum(INN)>600&&sum(INN)<1000)
    print("M2- Medium Risk customer")
if (sum(OUT) > 500&&sum(OUT)<800)
    print("M3- Medium Risk customer")
if(len(INN)+len(OUT)>10&&len(INN)+len(OUT)<20)
    print("M4- Medium Risk customer")

if(len(INN)<10&&len(OUT)<10)
    print("L1- Low Risk customer")
if(sum(INN)<600)
    print("L2- Low Risk customer")
if(sum(OUT)<500)
    print("L3- Low Risk customer")
if(len(INN)+len(OUT)<20)
    print("L4- Low Risk customer")